version: '3.8'
services:

# Frontend Container
  frontend:
    build: ./frontend/
    ports:
      - 21000:3000
    volumes:
      - ./frontend:/app
    networks:
      - frontend_backend

# Backend Container
  backend:
    build: ./backend/
    environment:
      DB_HOST: mysql://app:user@database:3306/fast_traiteur
    ports:
      - 21001:3000
    volumes:
      - ./backend/:/app:rw
    networks:
      - frontend_backend
      - backend_database
    depends_on:
      - database

# Database Container
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: app
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: fast_traiteur
    ports:
      - 21002:3306
    volumes:
      - dbdata:/var/lib/mysql:rw
    networks:
      - backend_database

# Volumes & Networks Declarations
# Volumes
volumes:
  dbdata:
# Networks
networks:
  frontend_backend:
  backend_database: 
  default:
    external: true
    name: none